// Import the types
import { NavLink } from '../types/navLinks';

// Site-related constants
export const SITE_TITLE = 'Phoenix Energy - Renewable Energy Solutions';
export const SITE_DESCRIPTION = 'Providing renewable energy solutions to help create a sustainable future.';

// Define constants for the paths in your app
export const HOME_PAGE = '/';
export const ABOUT_PAGE = '/about';
export const SOLUTIONS_PAGE = '#';
export const PROJECTS_PAGE = '/projects';
export const CONTACT_PAGE = '/contact-us';
export const SOLAR = '/solutions/embedded-systems';
export const WHEELING = '/solutions/wheeling';
export const CARBON_CREDITS = '/solutions/carbon-credits';
export const WASTE_VALOR = '/solutions/waste-valorization';
export const HYDROGEN = '/solutions/hydrogen-technologies';
export const CAREERS = 'https://linkedin.com/';
export const PRIVACY_POLICY = '/privacy-policy';

// Navigation links using the constants
export const NAV_LINKS: NavLink[] = [
    { name: 'About', path: ABOUT_PAGE, subMenu: [] },
    {
      name: 'Solutions',
      path: SOLUTIONS_PAGE,
      subMenu: [
        { name: 'Embedded Solar', path: SOLAR, category: 'save', icon: '/icons/Solar.svg' },
        { name: 'Wheeled Power', path: WHEELING, category: 'save', icon: '/icons/Wheeling.svg' },
        { name: 'Waste Valorization', path: WASTE_VALOR, category: 'earn' , icon: '/icons/Waste-Valorization.svg'},
        { name: 'Carbon Credits', path: CARBON_CREDITS, category: 'earn' , icon: '/icons/Carbon-Credits.svg'},
        { name: 'Hydrogen Technologies', path: HYDROGEN, category: 'save' , icon: '/icons/Hydrogen.svg'},
      ],
    },
    { name: 'Our Projects', path: PROJECTS_PAGE, subMenu: [] },
    { name: 'Contact', path: CONTACT_PAGE, subMenu: [] },
  ];


// Navigation links using the constants
export const COMPANY_LINKS = [
    { name: 'About', path: ABOUT_PAGE },
    { name: 'Our Projects', path: PROJECTS_PAGE},
    { name: 'Careers', path: CAREERS},
    { name: 'Contact', path: CONTACT_PAGE},
    { name: 'Privacy Policy', path: CONTACT_PAGE},
  ];

// URL-related constants
export const BASE_URL = 'https://phoenixenergy.tech';


// Other constants (e.g., API endpoints, contact info)
export const SOCIAL_PROFILES = [
    {account: 'linkedin', path: 'https://linkedin.com', icon: '/icons/linkedin.svg' },
    {account: 'facebook', path: 'https://facebook.com', icon: '/icons/facebook.svg' },
]
export const CONTACT_EMAIL = 'info@phoenixenergy.tech';
export const PHONE_NUMBER = '+123 456 7890';
export const ADDRESS = '123 Street, Johannesburg, South Africa';

//Carbon Credits Process
export interface ProcessSteps {
  title: string;
  description: string;
}

export const CarbonCreditsProcess: ProcessSteps[] = [
    {
      title: "Project Concept & Design",
      description: "Identify a project that reduces carbon emissions, an meets Verra's eligibilty criteria."
    },
    {
      title: "Prepare Project Design Document (PDD)",
      description: "The PDD outlines your project’s carbon reduction potential, baseline emissions, and monitoring plans."
    },
    {
      title: "Validation by Third Party Auditors",
      description: "An independent verifier reviews the PDD to ensure the project can deliver the expected emission reductions."
    },
    {
      title: "Project Registration",
      description: "Once validated, the project is registered with Verra and listed as an official carbon credit-generating project."
    },
    {
      title: "Monitoring & Verification",
      description: "Once the project is active, emission reductions must be monitored, reported and submitted to Verra for verification."
    },
    {
      title: "Issuance of Carbon Credits",
      description: "Once the reductions are verified, Verra issues carbon credits based on the amount of CO₂ reduced. These credits can then be traded or sold."
    }
  ];

  export const CarbonCreditsFAQs = [
    {
      question: "What are carbon credits?",
      answer: "Carbon credits are certificates that represent the reduction or removal of one metric ton of CO₂ or equivalent greenhouse gases, generated by sustainable projects like renewable energy or reforestation."
    },
    {
      question: "How do carbon credits work in South Africa?",
      answer: "In South Africa, carbon credits help businesses comply with the Carbon Tax Act of 2019, which imposes taxes on carbon emissions. Companies can use credits to reduce their tax liability by offsetting their emissions through certified projects like renewable energy or conservation efforts."
    },
    {
      question: "What is the difference between carbon credit and offset?",
      answer: "A carbon credit is a tradable certificate representing one ton of CO₂ emissions reduced or removed from the atmosphere through specific projects. It is often traded in regulated or voluntary carbon markets. A carbon offset, on the other hand, refers to the broader practice of compensating for emissions by investing in projects that reduce or capture CO₂, which may include purchasing carbon credits as one way of offsetting emissions. In short, carbon credits are specific units used within carbon offsetting projects."
    },
    {
      question: "How do carbon credits help businesses reduce emissions?",
      answer: "Businesses can buy carbon credits to offset their emissions, supporting projects that reduce or capture CO2, such as forest conservation or methane capture from landfills."
    },
    {
      question: "What is the difference between voluntary and compliance carbon markets?",
      answer: "In voluntary markets, companies choose to buy carbon credits to offset emissions, while compliance markets are regulated by governments and require companies to meet specific emissions caps."
    },
    {
      question: "Can businesses sell carbon credits?",
      answer: "Yes, businesses that generate surplus carbon credits through sustainability projects can sell them to other companies that need to offset their emissions."
    },
    {
      question: "How much is a carbon credit worth?",
      answer: "The value of a carbon credit varies depending on factors such as project type and market conditions. In South Africa, as of 2024, carbon credits are valued on average arounf R150 per ton of CO₂."
    }
    
  ]
  
  //Embedded System process Steps
  export const SolarProcess: ProcessSteps[] = [
    {
      "title": "Get in Touch",
      "description": "Contact us to discuss your goals and energy needs. Our team will guide you through the first steps and answer any questions you have."
    },
    {
      "title": "Energy Assessment",
      "description": "Send us your latest electricity bills, business address, and operating days. This helps us assess your energy usage and confirm the best solution for you."
    },
    {
      "title": "Initial Proposal",
      "description": "We’ll present a preliminary proposal outlining system options, expected savings, and potential financing, tailored to your business needs."
    },
    {
      "title": "Planning & Site Visit",
      "description": "Once the initial proposal has been accepted, our engineers will evaluate your property to confirm it can support the proposed solar design. We’ll assess any structural or electrical enhancements needed to safely install and integrate the system, ensuring long-term stability and compliance."
    },    
    {
      title: "Final Proposal",
      description: "With insights from the site visit, we’ll finalize your custom solar plan, including costs, timelines, and installation details."
    },
    {
      title: "Construction & Installation",
      description: "Our skilled team manages the installation with a focus on safety, compliance, and efficiency, ensuring a smooth transition to solar power."
    },
    {
      title: "Operation & Maintenance",
      description: "After installation, we provide ongoing monitoring and maintenance, ensuring your system delivers consistent, reliable energy."
    }
  ];

  export const SolarFAQs = [
    {
      "question": "What is a Power Purchase Agreement (PPA)?",
      "answer": "A Power Purchase Agreement (PPA) is a financing option where we install and maintain a solar system on your property at no upfront cost to you. Under a PPA, you pay only for the electricity the solar system generates, typically at a lower rate than standard grid electricity. This arrangement allows you to benefit from clean energy and cost savings without the responsibility of owning or maintaining the system."
    },    
    {
      question: "What is the expected payback period for a commercial solar system?",
      answer: "The payback period typically ranges from 4 to 8 years, depending on factors like system size and electricity usage. Our team can calculate the exact return on investment for your business, helping you understand when your system will start delivering savings."
    },
    {
      question: "What financing options are available for commercial solar installations?",
      answer: "We offer flexible financing options, including power purchase agreements (PPAs), solar loans, and leasing. With a PPA, you can get started with minimal upfront costs, while loans and leases offer other ownership benefits. Our team can guide you through the options and find the best fit for your budget and goals."
  },
    {
      question: "What tax incentives or rebates can South African businesses access for solar installations?",
      answer: "South Africa's Section 12B tax incentive allows businesses to deduct 100% of the cost of solar systems in the first year. This can make solar an even smarter investment. We can help you understand how to leverage this incentive for maximum savings on your project."
    },
    {
      question: "What maintenance is required for solar systems?",
      answer: "Solar systems require minimal maintenance, mainly periodic cleaning and inspections. We offer maintenance packages and extended warranties, ensuring your system performs optimally and stays reliable over the years. Let us handle the maintenance so you can focus on your business."
    },
    {
      question: "Can solar panels operate during frequent load-shedding?",
      answer: "Yes, with the right hybrid solar solution and battery backup, your business can operate seamlessly during load-shedding. We can design and install a system to keep your critical operations running, so you stay productive even when the grid is down."
    },
    {
      question: "Can excess energy generated by my solar system be sold back to the grid?",
      answer: `South Africa's regulations on selling energy to the grid vary. Some municipalities allow businesses to offset their utility costs with net metering, where excess energy is credited back to your account, lowering future bills.`
    }
    
  ]